/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) {
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value) {
            _modelo = value
        }
}

interface Perimetrable {
    fun calcularPerimetro(): Double
}

class Rectangulo(val ancho: Double, val alto: Double) : Perimetrable {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = ancho * alto
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    // Un método de la clase
    fun describir() {
        println("Este es un rectángulo.")
    }

    // Un método que realiza un cálculo
    override fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}

class Circulo(val radio: Double) : Perimetrable {
    override fun calcularPerimetro(): Double {
        return 2 * Math.PI * radio
    }
}

fun main() {

    val coche = Coche("Chevrolet", 2025)

    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")

    var rectangulo = Rectangulo(10.0, 5.0)

    println("Área ${rectangulo.area}")
    println("Perímetro ${rectangulo.calcularPerimetro()}")
    rectangulo.describir()

    var circulo = Circulo(4.0)

    val figuras: List<Perimetrable> = listOf(
        rectangulo,
        circulo
    )

    println("Perímetros de las figuras:")
    for (figura in figuras) {
        println(figura.calcularPerimetro())
    }
}